const myLightTheme = {
  // palette: {
  //   themePrimary: "#3fbd00",
  //   themeLighterAlt: "#f6fcf2",
  //   themeLighter: "#daf4cd",
  //   themeLight: "#bceba5",
  //   themeTertiary: "#81d756",
  //   themeSecondary: "#51c518",
  //   themeDarkAlt: "#39aa00",
  //   themeDark: "#308f00",
  //   themeDarker: "#236a00",
  //   neutralLighterAlt: "#f1f1f1",
  //   neutralLighter: "#ededed",
  //   neutralLight: "#e3e3e3",
  //   neutralQuaternaryAlt: "#d3d3d3",
  //   neutralQuaternary: "#cacaca",
  //   neutralTertiaryAlt: "#c2c2c2",
  //   neutralTertiary: "#a19f9d",
  //   neutralSecondary: "#605e5c",
  //   neutralPrimaryAlt: "#3b3a39",
  //   neutralPrimary: "#323130",
  //   neutralDark: "#201f1e",
  //   black: "#000000",
  //   white: "#f7f7f7",
  // },
  palette: {
    themePrimary: "#118cf7",
    themeLighterAlt: "#f5faff",
    themeLighter: "#d8ecfe",
    themeLight: "#b6dcfd",
    themeTertiary: "#6fb9fa",
    themeSecondary: "#2d99f8",
    themeDarkAlt: "#107edf",
    themeDark: "#0d6abc",
    themeDarker: "#0a4e8b",
    neutralLighterAlt: "#f1f1f1",
    neutralLighter: "#ededed",
    neutralLight: "#e3e3e3",
    neutralQuaternaryAlt: "#d3d3d3",
    neutralQuaternary: "#cacaca",
    neutralTertiaryAlt: "#c2c2c2",
    neutralTertiary: "#a19f9d",
    neutralSecondary: "#605e5c",
    neutralPrimaryAlt: "#3b3a39",
    neutralPrimary: "#323130",
    neutralDark: "#201f1e",
    black: "#000000",
    white: "#f7f7f7",
  },
};
export default myLightTheme;
